Use colors when logging. Logging statements can now be logged to a file as well.

diff --git a/ec2debian-build-ami b/ec2debian-build-ami
--- a/ec2debian-build-ami
+++ b/ec2debian-build-ami
@@ -6,10 +6,40 @@
 scriptdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 originaldir=$(/bin/pwd)
 
+# Define some colors
+txtdef="\e[0m"    # revert to default color
+bldred="\e[1;31m" # bold red
+txtblu="\e[0;34m" # blue
+
+logfile=''
+logcolor=$txtblu
+errfile=''
+errcolor=$bldred
+
+# Logging function
+function log {
+	for line in "$@"; do
+		out "$logcolor$line$txtdef\n" "$line\n" $logfile
+	done
+}
+
+function logn {
+	out "$logcolor$1$txtdef" "$1" $logfile
+}
+
 # Custom die function, output to stderr instead of stdout
 function die {
-	echo -e $@ >&2
+	for line in "$@"; do
+		out "$errcolor$line$txtdef\n" "$line\n" $errfile >&2
+	done
 	exit 1
+}
+
+function out {
+	printf -- "$1"
+	if [ -n "$3" ]; then
+		printf -- "$2" >>$3
+	fi
 }
 
 # Wait for the execution of $cmd not to return an empty string
@@ -19,11 +49,11 @@ function dotdot {
 	sleep=5
 	[ ! -z "$3" ] && sleep=$3
 	while [ -z "$status" ]; do
-		echo -n '.'
+		logn '.'
 		sleep $sleep
 		status=`eval $cmd`
 	done
-	echo
+	logn "\n"
 }
 
 # Add some standard packages we are going to need
@@ -64,20 +94,21 @@ true ${AWS_USER_ID:?} ${AWS_ACCESS_KEY_ID:?} ${AWS_SECRET_ACCESS_KEY:?} \
 [[ $arch != 'amd64' && $arch != 'i386' ]] && die "$0: Unrecognized architecture: $arch"
 
 # Quit if we can't find the certificate
-[ ! -f "$EC2_CERT" ] && die "$0: AWS certificate file not found: $EC2_CERT"
+[ ! -f "$EC2_CERT" ] && die "$0: AWS certificate file not found:" "$EC2_CERT"
 export EC2_CERT
 
 # ... or the private for.
-[ ! -f "$EC2_PRIVATE_KEY" ] && die "$0: AWS private key file not found: $EC2_PRIVATE_KEY"
+[ ! -f "$EC2_PRIVATE_KEY" ] && die "$0: AWS private key file not found:" "$EC2_PRIVATE_KEY"
 export EC2_PRIVATE_KEY
 
 # Output some info to the user about the AMI we are about to build
-echo "Building AMI for $distribution $codename"
-echo "locale:         $locale"
-echo "charmap:        $charmap"
-echo "timezone:       $timezone"
-echo "architecture:   $arch"
-echo "packages:       $packages"
+log \
+	"Building AMI for $distribution $codename" \
+	"locale:       $locale" \
+	"charmap:      $charmap" \
+	"timezone:     $timezone" \
+	"architecture: $arch" \
+	"packages:     $packages"
 
 # Source all tasks in the right order
 for task in `find $scriptdir/tasks -type f | sort`; do
