Fail if euca2ools make fails

diff --git a/tasks/05-host-dependencies b/tasks/05-host-dependencies
--- a/tasks/05-host-dependencies
+++ b/tasks/05-host-dependencies
@@ -11,4 +11,11 @@ if [ ! -d $scriptdir/euca2ools ]; then
 	curl -s -L -o $scriptdir/euca2ools-1.3.2.tar.gz https://github.com/eucalyptus/euca2ools/archive/1.3.2.tar.gz
 	tar zxf $scriptdir/euca2ools-1.3.2.tar.gz
 fi
-(cd euca2ools-1.3.2; make)
+
+# We want to fail if make fails, so don't start a subshell with ()
+# Remember the old dir
+pwd_before_euca_make=$(pwd)
+cd euca2ools-1.3.2
+make | spin
+[ $PIPESTATUS == 0 ] || die "Bootstrapping failed!"
+cd $pwd_before_euca_make
