Only install euca2ools when necessary

diff --git a/tasks/05-host-dependencies b/tasks/05-host-dependencies
--- a/tasks/05-host-dependencies
+++ b/tasks/05-host-dependencies
@@ -12,10 +12,19 @@ if [ ! -d $scriptdir/euca2ools ]; then
 	tar zxf $scriptdir/euca2ools-1.3.2.tar.gz
 fi
 
-# We want to fail if make fails, so don't start a subshell with ()
-# Remember the old dir
-pwd_before_euca_make=$(pwd)
-cd euca2ools-1.3.2
-make | spin
-[ $PIPESTATUS == 0 ] || die "Bootstrapping failed!"
-cd $pwd_before_euca_make
+function install_euca2ools {
+	# We want to fail if make fails, so don't start a subshell with ()
+	# Remember the old dir
+	local orig_pwd=$(pwd)
+	cd euca2ools-1.3.2
+	make | spin
+	[ $PIPESTATUS == 0 ] || die "Bootstrapping failed!"
+	cd $orig_pwd
+}
+
+# make the euca2ools if they are not installed or the version is wrong
+if ! command -v euca-version > /dev/null 2>&1; then
+	install_euca2ools
+elif [[ ! "`euca-version`" =~ euca2ools\ 1.3.* ]]; then
+	install_euca2ools
+fi
