Fail when boto cannot be patched

diff --git a/tasks/06-patch-boto b/tasks/06-patch-boto
--- a/tasks/06-patch-boto
+++ b/tasks/06-patch-boto
@@ -9,6 +9,7 @@ function apply_boto_patch {
 			echo $?)
 		if [ $result -eq 0 ]; then
 			wget -qO $patch_url | patch -sfr - -d $boto_ec2_dir
+			[ $PIPESTATUS == 0 ] || die "Unable to patch boto."
 		fi
 	fi
 }
