Fail when instance metadata cannot be fetched.

diff --git a/tasks/create-volume b/tasks/create-volume
--- a/tasks/create-volume
+++ b/tasks/create-volume
@@ -8,8 +8,19 @@ if [ -n "`df | grep $device_path`" ]; then
 	exit
 fi
 
-instance_id=`curl --silent http://169.254.169.254/latest/meta-data/instance-id`
-availability_zone=`curl --silent http://169.254.169.254/latest/meta-data/placement/availability-zone`
+metadata_url='http://169.254.169.254/latest/meta-data'
+instance_id=`curl --silent $metadata_url/instance-id`
+availability_zone=`curl --silent $metadata_url/placement/availability-zone`
+
+if [ -z "$instance_id" ]; then
+	echo "Unable to fetch the instance id of this machine." >&2
+	echo "This script must be running on ec2 in order to mount EBS volumes." >$2
+	exit 1
+fi
+if [ -z "$availability_zone" ]; then
+	echo "Unable to fetch the availability zone of this machine." >&2
+	exit 1
+fi
 
 if [ -z "$volume_id" ]; then
 	echo "No volume id specified, creating a volume now."
